### ISSUE TITLE
Cheirality constraint

### ISSUE THREAD

**Issue by rjanvier** [mergarsal/FastCertRelPose#1]
Hi,
Thank for sharing your work.
I tested the solver many times and I found that it output some time solutions with points behind the cameras. I know chirality constraints are checked on minimal solver but, maybe I'm wrong, you do not mention this in your paper. Is it a known "issue" of your formulation ? If yes is there any mechanism your lib to mitigate this or should I rely on my own ?
Thank in advance !

**Comment by rjanvier** [comment]
Ok, my bad it's usually checked E decomposition to Rt. and it seems to be checked as well on your code in EssentialUtils.cpp. But still, I observe it output some inverse translation.

**Comment by rjanvier** [comment]
This behavior is even verifiable with the sample provided:
_example_essential_matrix_

`Ground truth rotation:
 0.911857 -0.405438 0.0643213
 0.387774  0.799297 -0.459082
 0.134717  0.443559  0.886062
**Ground truth translation Tgt:
-0.893468
 0.259222
-0.366769**

-------------------------
Running algotihm on-manifold estimation
 Constructing data matrix C.
Initial estimate from linear estimation (8pts):
 0.178468  0.411334 0.0617123
-0.215087  0.546681  0.765619
-0.584085 -0.605706  0.394734
Choosing initial guess:

8 points guess ...
Initial guess rotation:
 0.911995 -0.405237 0.0636194
 0.386939  0.798382 -0.461372
 0.136172  0.445386  0.884923
Initial guess translation Tgt:
 **0.891709
 -0.262115
 0.368986**
Recovering R & t from E:
R :
 0.911995 -0.405237 0.0636194
 0.386939  0.798382 -0.461372
 0.136172  0.445386  0.884923
t:
 0.891709
-0.262115
 0.368986
 
 ....
 
 Recovered R:
  0.91178 -0.405763 0.0633547
 0.387414  0.798645 -0.460518
 0.136263  0.444436  0.885386

 **Recovered t:
 0.891649
-0.262351
 0.368963**`

**Comment by mergarsal** [comment]
Hi, Thanks for letting me know. We do check the cheirality constraint during the pose recovery for completeness with the algorithm proposed in ''Equivalent Constraints for Two-View Geometry: Pose Solution/Pure
Rotation Identification and 3D Reconstruction by Qi Cai, Yuanxin Wu, Lilian Zhang, Peike Zhang'' which doesn't require to triangulate the points. I can only suggest to leverage another algorithm for the recovering (e.g., triangulate the points with both solutions and check the positive depth of the points).

**Comment by rjanvier** [comment]
Thank for your answer and the ref to the paper, I will look a it. 

I plugged your solver into the global pipeline of [OpenMVG](https://github.com/openMVG/openMVG).  By using a triangulation based orientation check on FastCertRelPose output, I'm able to have consistent results (minus a detail but it may be the subject of another question) which is not the case with the Rt output taken directly from the solver.

**Comment by bayesyf** [comment]
@mergarsal hello，i have searched your answers by google about the paper  ''Equivalent Constraints for Two-View Geometry: Pose Solution/Pure Rotation Identification and 3D Reconstruction by Qi Cai, Yuanxin Wu, Lilian Zhang, Peike Zhang'',would you please check the equation (18) et×h×et=h，is this wrong? thanks

**Comment by mergarsal** [comment]
Hello, that reference is not my work, I can only answer about my
implementation. Let me know if you have any problem with the code
