### ISSUE TITLE
cmake problem

### ISSUE THREAD

**Issue by Rurinn** [mergarsal/FastCertRelPose#2]
Hi,
Thank for sharing your work.

when I try to cmake I encountered an error:
CMake Error: install(EXPORT "EssentialExport" ...) includes target "Essential" which requires target "Optimization" that is not in any export set.
I have cmake the Optimization denpendency but the error still remained.
I am not familiar with cmake so I want to know how to fix this.
Thanks!

**Comment by mergarsal** [comment]
Hi, 
Thanks for letting me know! Commit 34f3a9e should work now
